# Generated by Django 3.1.6 on 2021-12-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('user_id', models.UUIDField(primary_key=True, serialize=False)),
                ('last_calculated', models.DateTimeField()),
                ('rank', models.IntegerField(default=0)),
                ('rank_points', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('attended', models.IntegerField(default=0)),
                ('total_games', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('year_wins', models.IntegerField(default=0)),
                ('year_attended', models.IntegerField(default=0)),
                ('year_total_games', models.IntegerField(default=0)),
                ('year_total_score', models.IntegerField(default=0)),
                ('data_tournaments', models.BinaryField()),
                ('data_top_five_tournaments', models.BinaryField()),
                ('data_year_top_five_tournaments', models.BinaryField()),
            ],
        ),
    ]
