# Generated by Django 3.1.6 on 2022-01-04 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20220102_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='statistics', serialize=False, to='accounts.user')),
                ('last_calculated', models.DateTimeField()),
                ('rank', models.IntegerField(default=0)),
                ('rank_points', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('attended', models.IntegerField(default=0)),
                ('total_games', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('year_wins', models.IntegerField(default=0)),
                ('year_attended', models.IntegerField(default=0)),
                ('year_total_games', models.IntegerField(default=0)),
                ('year_total_score', models.IntegerField(default=0)),
                ('data_tournaments', models.BinaryField()),
                ('data_top_five_tournaments', models.BinaryField()),
                ('data_year_top_five_tournaments', models.BinaryField()),
            ],
        ),
    ]
