# Generated by Django 3.1.6 on 2022-01-15 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='last_calculated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
