# Generated by Django 3.1.6 on 2021-07-28 07:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oil_Pattern',
            fields=[
                ('pattern_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('pattern_name', models.TextField()),
                ('pattern_cache', models.JSONField()),
                ('pattern_db_id', models.IntegerField()),
            ],
        ),
    ]
