# Generated by Django 3.1.6 on 2021-08-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oil_pattern',
            name='pattern_backward',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='oil_pattern',
            name='pattern_forward',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='oil_pattern',
            name='pattern_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='oil_pattern',
            name='pattern_ratio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='oil_pattern',
            name='pattern_volume',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='oil_pattern',
            name='pattern_cache',
            field=models.JSONField(default=0),
        ),
        migrations.AlterField(
            model_name='oil_pattern',
            name='pattern_db_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='oil_pattern',
            name='pattern_name',
            field=models.TextField(default=0),
        ),
    ]
