# Generated by Django 3.1.6 on 2021-09-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oils', '0002_auto_20210801_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oil_pattern',
            name='pattern_cache',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
