# Generated by Django 3.1.6 on 2022-01-04 19:36

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vod',
            fields=[
                ('vod_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('video', models.FileField(default='vods/default.mp4', upload_to='vods/')),
                ('poster', models.ImageField(default='vod-posters/default.jpg', upload_to='vod-posters/')),
                ('date_joined', models.DateField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
