# Generated by Django 3.1.6 on 2021-11-22 21:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vod',
            fields=[
                ('vod_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('video', models.FileField(default='vods/default.mp4', upload_to='vods/')),
                ('poster', models.ImageField(default='vod-posters/default.jpg', upload_to='vod-posters/')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
