# Generated by Django 3.1.6 on 2021-07-06 07:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournament_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tournament_name', models.CharField(max_length=100)),
                ('tournament_description', models.TextField(blank=True, null=True)),
                ('tournament_date', models.DateField(blank=True, null=True)),
                ('tournament_time', models.TimeField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, upload_to='')),
                ('center', models.UUIDField(blank=True, null=True, unique=True)),
                ('format', models.UUIDField(blank=True, null=True, unique=True)),
                ('entry_fee', models.FloatField(blank=True, null=True)),
                ('total_games', models.IntegerField(default=0)),
                ('placements', models.JSONField(blank=True, null=True)),
                ('sponsor_image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
