# Generated by Django 3.1.6 on 2021-07-06 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='sponsor_image',
        ),
    ]
