# Generated by Django 3.1.6 on 2022-01-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournamentdata_is_winner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='tournament_id',
            new_name='id',
        ),
    ]
