# Generated by Django 3.1.6 on 2021-07-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_auto_20210706_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='total_games',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
