# Generated by Django 3.1.6 on 2021-07-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_auto_20210706_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='sponsor_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
