# Generated by Django 3.1.6 on 2021-07-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_tournament_sponsor_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='placements',
            new_name='matchplay',
        ),
        migrations.AddField(
            model_name='tournament',
            name='qualifiers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
