# Generated by Django 3.1.6 on 2021-09-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_auto_20210711_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournament_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
