# Generated by Django 3.1.6 on 2021-09-19 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_tournament_tournament_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
