# Generated by Django 3.1.6 on 2021-09-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_auto_20210918_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='placement_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
