# Generated by Django 3.1.6 on 2021-09-25 08:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_tournament_placement_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('sponsor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sponsor_name', models.CharField(blank=True, max_length=60, null=True)),
                ('sponsor_display_name', models.CharField(blank=True, max_length=60, null=True)),
                ('sponsor_balance', models.IntegerField(blank=True, default=0)),
                ('sponsor_image', models.ImageField(default='sponsor-pictures/default.jpg', upload_to='sponsor-pictures/')),
            ],
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='sponsor_image',
        ),
        migrations.AddField(
            model_name='tournament',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='live_status_header',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='live_status_leader',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='live_status_leader_score',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='roster',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='sponsor',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='spots_reserved',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='stream_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='picture',
            field=models.ImageField(default='tournament-pictures/default.jpg', upload_to='tournament-pictures/'),
        ),
    ]
