# Generated by Django 3.1.6 on 2021-09-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_auto_20210925_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='center',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
