# Generated by Django 3.1.6 on 2021-09-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_auto_20210928_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='oil_pattern',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
