# Generated by Django 3.1.6 on 2021-09-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_tournament_oil_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='vod_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
