# Generated by Django 3.1.6 on 2021-11-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_tournament_vod_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='scrape_center',
            field=models.TextField(default=''),
        ),
    ]
