# Generated by Django 3.1.6 on 2021-11-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0014_tournament_scrape_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='scrape_center',
        ),
        migrations.AddField(
            model_name='tournament',
            name='picture_scrape',
            field=models.TextField(default=''),
        ),
    ]
