# Generated by Django 3.1.6 on 2021-12-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_auto_20211127_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='double',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='soup',
            field=models.TextField(default=''),
        ),
    ]
