# Generated by Django 3.1.6 on 2021-12-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0017_auto_20211208_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringData',
            fields=[
                ('tournament_id', models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='center',
            new_name='center_id',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='roster',
            new_name='data_roster',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='tournament_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='format',
            new_name='format_id',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='tournament_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_date',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_time',
        ),
        migrations.AddField(
            model_name='tournament',
            name='data_scoring',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='scoring_data_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
