# Generated by Django 3.1.6 on 2021-12-16 00:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0018_auto_20211213_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('game_data_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('tournament_id', models.UUIDField()),
                ('game_number', models.SmallIntegerField(default=0)),
                ('lane', models.SmallIntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('data_raw_scores', models.BinaryField()),
                ('data_scores', models.BinaryField()),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='ScoringData',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='picture_scrape',
        ),
        migrations.AddField(
            model_name='tournament',
            name='scraped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='soup_url',
            field=models.TextField(default=''),
        ),
    ]
