# Generated by Django 3.1.6 on 2021-12-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0020_auto_20211216_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
