# Generated by Django 3.1.6 on 2021-12-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0021_auto_20211216_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamedata',
            name='match_number',
            field=models.SmallIntegerField(default=0),
        ),
    ]
