# Generated by Django 3.1.6 on 2021-12-19 07:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0022_auto_20211216_0703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('format_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
                ('is_qualifiers', models.BooleanField()),
                ('qualifier_games', models.SmallIntegerField(default=0)),
                ('cashers', models.SmallIntegerField(default=0)),
                ('is_carryover', models.BooleanField(default=False)),
                ('is_bonus_pins', models.BooleanField(default=False)),
            ],
        ),
    ]
