# Generated by Django 3.1.6 on 2021-07-03 02:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('finish_profile', models.BooleanField(default=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('picture', models.URLField(blank=True, null=True)),
                ('location_street', models.TextField(blank=True, null=True)),
                ('location_city', models.TextField(blank=True, null=True)),
                ('location_state', models.TextField(blank=True, null=True)),
                ('location_zip', models.IntegerField(blank=True, null=True)),
                ('hand', models.IntegerField(blank=True, null=True)),
                ('medals', models.JSONField(blank=True, null=True)),
                ('tournaments', models.JSONField(blank=True, null=True)),
                ('statistics', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
