# Generated by Django 3.1.6 on 2022-01-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220102_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_drawer_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
