# Generated by Django 3.1.6 on 2021-07-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210703_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location_zip',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile-pictures/'),
        ),
    ]
