# Generated by Django 3.1.6 on 2021-07-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210703_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='profile-pictures/default.jpg', upload_to='profile-pictures/'),
        ),
    ]
