# Generated by Django 3.1.6 on 2021-07-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210703_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='media/profile-pictures/default.jpg', upload_to='media/profile-pictures/'),
        ),
    ]
