# Generated by Django 3.1.6 on 2021-07-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210703_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
