# Generated by Django 3.1.6 on 2021-09-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_shorten'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ask_for_claim',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='unclaimed',
            field=models.BooleanField(default=False),
        ),
    ]
