# Generated by Django 3.1.6 on 2021-09-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210917_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='statistics',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tournaments',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
