# Generated by Django 3.1.6 on 2021-12-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_soup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='friends',
            new_name='data_friends',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='tournaments',
            new_name='data_tournaments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='statistics',
        ),
        migrations.AddField(
            model_name='user',
            name='data_blocked',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
