# Generated by Django 3.1.6 on 2021-12-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20211213_0517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can', 'Can eat pizzas')]},
        ),
        migrations.RemoveField(
            model_name='user',
            name='left_handed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='right_handed',
        ),
        migrations.AddField(
            model_name='user',
            name='handed',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_bowler_of_month',
            field=models.BooleanField(default=False),
        ),
    ]
