# Generated by Django 3.1.6 on 2021-12-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20211215_0209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='scraped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='soup_url',
            field=models.TextField(default=''),
        ),
    ]
