# Generated by Django 3.1.6 on 2021-12-21 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20211219_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='location_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='location_street',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='location_zip',
            new_name='zip',
        ),
    ]
