# Generated by Django 3.1.6 on 2021-12-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_friend_requests_inbound',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='data_friend_requests_outbound',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
