# Generated by Django 3.1.6 on 2021-12-25 08:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20211224_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('recipient', models.UUIDField(blank=True, null=True)),
                ('sender', models.UUIDField(blank=True, null=True)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2021, 12, 25, 8, 11, 24, 832516, tzinfo=utc))),
                ('title', models.CharField(max_length=5)),
                ('body', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=20)),
                ('read', models.BooleanField(default=False)),
                ('data', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
