# Generated by Django 3.1.6 on 2021-12-25 10:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_push_tokens',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 25, 10, 48, 55, 598585, tzinfo=utc)),
        ),
    ]
