# Generated by Django 3.1.6 on 2021-12-25 11:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20211225_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 25, 11, 5, 58, 326747, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='data_push_tokens',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
