# Generated by Django 3.1.6 on 2021-12-25 11:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20211225_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='data',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='notification',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 25, 11, 44, 29, 758442, tzinfo=utc)),
        ),
    ]
