# Generated by Django 3.1.6 on 2021-12-28 12:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20211225_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 28, 12, 8, 38, 709571, tzinfo=utc)),
        ),
    ]
