# Generated by Django 3.1.6 on 2021-12-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medal_id', models.CharField(max_length=30)),
                ('medal_name', models.TextField()),
                ('medal_description', models.TextField()),
                ('icon', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SeasonRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_id', models.CharField(max_length=30)),
                ('total_games', models.IntegerField()),
                ('total_bowlers', models.IntegerField()),
                ('tournaments', models.JSONField()),
                ('bowlers', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.CharField(max_length=30)),
                ('series_name', models.TextField()),
                ('series_description', models.TextField()),
                ('use_decay', models.BooleanField()),
                ('count_placement', models.BooleanField()),
                ('count_score', models.BooleanField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('tournaments', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SeriesRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.CharField(max_length=30)),
                ('total_games', models.IntegerField()),
                ('total_bowlers', models.IntegerField()),
                ('tournaments', models.JSONField()),
                ('bowlers', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='WebData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_tournament', models.UUIDField(blank=True, null=True)),
            ],
        ),
    ]
