# Generated by Django 3.1.6 on 2021-12-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScratchBowling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webdata',
            name='bowler_of_month',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
