# Generated by Django 3.1.6 on 2021-12-09 01:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('clip_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('vod_id', models.UUIDField(blank=True, null=True)),
                ('clip_source', models.TextField(default='')),
                ('title', models.TextField(default='Default Clip Title')),
                ('description', models.TextField(default='Default Clip Description')),
            ],
        ),
        migrations.CreateModel(
            name='FullVod',
            fields=[
                ('vod_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('stream_id', models.UUIDField(blank=True, null=True)),
                ('vod_source', models.TextField(default='')),
                ('vod_mirror', models.TextField(default='')),
                ('title', models.TextField(default='Default Vod Title')),
                ('description', models.TextField(default='Default Vod Description')),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('stream_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tournament_id', models.UUIDField(blank=True, null=True)),
                ('vod_id', models.UUIDField(blank=True, null=True)),
                ('stream_source', models.TextField(default='')),
                ('stream_mirror', models.TextField(default='')),
                ('title', models.TextField(default='Default Stream Title')),
                ('description', models.TextField(default='Default Stream Description')),
            ],
        ),
    ]
