# Generated by Django 3.1.6 on 2022-01-04 06:23

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('clip_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('vod_id', models.UUIDField(blank=True, null=True)),
                ('clip_source', models.TextField(default='')),
                ('thumbnail_image', models.ImageField(default='broadcast-thumbnails/clips/default.jpg', upload_to='broadcast-thumbnails/clips/')),
                ('title', models.TextField(default='Default Clip Title')),
                ('description', models.TextField(default='Default Clip Description')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('duration', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FullVod',
            fields=[
                ('vod_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('stream_id', models.UUIDField(blank=True, null=True)),
                ('vod_source', models.TextField(default='')),
                ('vod_mirror', models.TextField(default='')),
                ('thumbnail_image', models.ImageField(default='broadcast-thumbnails/vods/default.jpg', upload_to='broadcast-thumbnails/vods/')),
                ('title', models.TextField(default='Default Vod Title')),
                ('description', models.TextField(default='Default Vod Description')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('duration', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('stream_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tournament_id', models.UUIDField(blank=True, null=True)),
                ('vod_id', models.UUIDField(blank=True, null=True)),
                ('stream_source', models.TextField(default='')),
                ('stream_mirror', models.TextField(default='')),
                ('thumbnail_image', models.ImageField(default='broadcast-thumbnails/streams/default.jpg', upload_to='broadcast-thumbnails/streams/')),
                ('title', models.TextField(default='Default Stream Title')),
                ('description', models.TextField(default='Default Stream Description')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('uptime', models.IntegerField(default=0)),
            ],
        ),
    ]
