# Generated by Django 3.1.6 on 2021-12-09 02:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0002_auto_20211208_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='clip',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fullvod',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='fullvod',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stream',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='stream',
            name='uptime',
            field=models.IntegerField(default=0),
        ),
    ]
