# Generated by Django 3.1.6 on 2022-01-11 12:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('center_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('center_name', models.TextField()),
                ('center_description', models.TextField()),
                ('location_street', models.TextField()),
                ('location_city', models.TextField()),
                ('location_state', models.TextField()),
                ('location_zip', models.IntegerField(default=0)),
                ('phone_number', models.IntegerField(default=0)),
                ('oil_machine', models.TextField(default='')),
                ('picture', models.ImageField(default='center-pictures/default.jpg', upload_to='center-pictures/')),
                ('scraped', models.BooleanField(default=False)),
                ('soup_url', models.TextField(default='')),
                ('soup', models.TextField(default='')),
            ],
        ),
    ]
