# Generated by Django 3.1.6 on 2021-07-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='oil_machine',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='center',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='center',
            name='tournaments',
            field=models.JSONField(default=''),
        ),
        migrations.AlterField(
            model_name='center',
            name='location_zip',
            field=models.IntegerField(default=0),
        ),
    ]
