# Generated by Django 3.1.6 on 2021-08-03 08:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_auto_20210731_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='id',
        ),
        migrations.AlterField(
            model_name='center',
            name='center_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
