# Generated by Django 3.1.6 on 2021-12-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0003_auto_20210803_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='picture',
            field=models.ImageField(default='center-pictures/default.jpg', upload_to='center-pictures/'),
        ),
    ]
