# Generated by Django 3.1.6 on 2021-12-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0004_center_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='scraped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='center',
            name='soup',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='center',
            name='soup_url',
            field=models.TextField(default=''),
        ),
    ]
